apiVersion: v2
name: rafiki-auth
description: Rafiki Auth Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.5.0
appVersion: "v1.0.0-alpha.7"

dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
    # import-values:
    #   - child: securityContext
    #     parent: securityContext
    #   - child: podSecurityContext
    #     parent: podSecurityContext

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
